name = "Cozy Chaos"
author = "Michael Wenk"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5c5e97003a9b58d3a030d93f78d0eb3d6019929ac0d6975d2e5c42bbfac0e2b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
