name = "Cozy Chaos"
author = "Michael Wenk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f1fcdeca38a66f53a2aed3d53ef396621b14f54d66502e156b5fd11b992acba"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
