name = "Cozy Chaos"
author = "Michael Wenk"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03c299640c573434509deaba8a71d8d1bc221adcd3ec713e2198d9703e9e476f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
